{
  "uid" : "421c3eeb9727faa1",
  "name" : "test_002",
  "fullName" : "TestCases.test_01.TestExchange#test_002",
  "historyId" : "4852f8a856c7054b2bc974c95a71170a",
  "time" : {
    "start" : 1589526807945,
    "stop" : 1589526807945,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "AttributeError: 'dict' object has no attribute 'append'",
  "statusTrace" : "self = <Utils.Assert.Assert object at 0x03B2B310>, body = 1, assert_body = 2\n\n    def assert_body(self,body,assert_body):\n        '''\n        请求响应body断言\n        :data body:\n        :data assert_body:\n        :return:\n        '''\n        try:\n>           assert body == assert_body\nE           AssertionError\n\nUtils\\Assert.py:37: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <TestCases.test_01.TestExchange object at 0x03B2B430>\n\n    @allure.story('用例2')\n    def test_002(self):\n        _assert = Assert.Assert()\n>       assert _assert.assert_body(1,2)\n\nTestCases\\test_01.py:64: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <Utils.Assert.Assert object at 0x03B2B310>, body = 1, assert_body = 2\n\n    def assert_body(self,body,assert_body):\n        '''\n        请求响应body断言\n        :data body:\n        :data assert_body:\n        :return:\n        '''\n        try:\n            assert body == assert_body\n            return True\n        except:\n            self.log.error(\"响应body对比失败，响应body为:{0},断言body为:{1}\".format(body,assert_body))\n>           Constans.RESULT_LIST.append('fail')\nE           AttributeError: 'dict' object has no attribute 'append'\n\nUtils\\Assert.py:41: AttributeError",
  "flaky" : false,
  "beforeStages" : [ ],
  "testStage" : {
    "status" : "broken",
    "statusMessage" : "AttributeError: 'dict' object has no attribute 'append'",
    "statusTrace" : "self = <Utils.Assert.Assert object at 0x03B2B310>, body = 1, assert_body = 2\n\n    def assert_body(self,body,assert_body):\n        '''\n        请求响应body断言\n        :data body:\n        :data assert_body:\n        :return:\n        '''\n        try:\n>           assert body == assert_body\nE           AssertionError\n\nUtils\\Assert.py:37: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <TestCases.test_01.TestExchange object at 0x03B2B430>\n\n    @allure.story('用例2')\n    def test_002(self):\n        _assert = Assert.Assert()\n>       assert _assert.assert_body(1,2)\n\nTestCases\\test_01.py:64: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <Utils.Assert.Assert object at 0x03B2B310>, body = 1, assert_body = 2\n\n    def assert_body(self,body,assert_body):\n        '''\n        请求响应body断言\n        :data body:\n        :data assert_body:\n        :return:\n        '''\n        try:\n            assert body == assert_body\n            return True\n        except:\n            self.log.error(\"响应body对比失败，响应body为:{0},断言body为:{1}\".format(body,assert_body))\n>           Constans.RESULT_LIST.append('fail')\nE           AttributeError: 'dict' object has no attribute 'append'\n\nUtils\\Assert.py:41: AttributeError",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "ddb4cd8fa4dc3851",
      "name" : "log",
      "source" : "ddb4cd8fa4dc3851.txt",
      "type" : "text/plain",
      "size" : 106
    } ],
    "parameters" : [ ],
    "attachmentsCount" : 1,
    "shouldDisplayMessage" : true,
    "hasContent" : true,
    "stepsCount" : 0
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "story",
    "value" : "用例2"
  }, {
    "name" : "feature",
    "value" : "小额资产兑换"
  }, {
    "name" : "parentSuite",
    "value" : "TestCases"
  }, {
    "name" : "suite",
    "value" : "test_01"
  }, {
    "name" : "subSuite",
    "value" : "TestExchange"
  }, {
    "name" : "host",
    "value" : "DESKTOP-8TLGUH8"
  }, {
    "name" : "thread",
    "value" : "9008-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "TestCases.test_01"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "421c3eeb9727faa1.json",
  "parameterValues" : [ ]
}